/**
 * UCLA Dining.
 *
 * There is no API. dining.ucla.edu runs WordPress but every `/wp-json/` route
 * returns 401, there is no RSS feed, and no JSON-LD or embedded payload exists.
 * What remains is the public HTML, which robots.txt explicitly permits crawling
 * (only /wp-admin/ is disallowed).
 *
 * This adapter therefore parses two public pages:
 *   https://dining.ucla.edu/hours/                        — the hours table
 *   https://dining.ucla.edu/menus-at-a-glance/?date=...    — menus for one date
 *
 * The markup is generated by UCLA's Jamix menu plugin and uses stable, semantic
 * class names, but it is still markup: an upstream redesign will break parsing.
 * When that happens the adapter returns an empty or error result and the UI
 * shows an unavailable state — it never invents a menu.
 */

import * as cheerio from 'cheerio';

import { SOURCES } from '@/lib/config/sources';
import { fetchText } from '@/lib/net/fetch-json';
import { campusDate, campusWallClockToIso, makeId, slugify } from '@/lib/normalize';
import type {
  DiningDay,
  DiningHours,
  DiningMenuItem,
  DiningMenuSection,
  DiningVenue,
  MealPeriod,
  MediaItem,
  SourceResult,
} from '@/lib/types';
import { MEAL_PERIOD_LABELS } from '@/lib/types';

const SOURCE_ID = 'dining';

const ORIGIN = 'https://dining.ucla.edu';
const HOURS_URL = `${ORIGIN}/hours/`;
const MENU_URL = `${ORIGIN}/menus-at-a-glance/`;

/** The hours table's column headings, mapped to our meal-period vocabulary. */
const COLUMN_TO_PERIOD: Record<string, MealPeriod> = {
  breakfast: 'breakfast',
  brunch: 'brunch',
  lunch: 'lunch',
  dinner: 'dinner',
  'extended dinner': 'late-night',
  'late night': 'late-night',
};

/** The menu page's section anchors, mapped the same way. */
const ANCHOR_TO_PERIOD: Record<string, MealPeriod> = {
  breakfastmenu: 'breakfast',
  brunchmenu: 'brunch',
  lunchmenu: 'lunch',
  dinnermenu: 'dinner',
  extendeddinnermenu: 'late-night',
  latenightmenu: 'late-night',
};

/** Parse "7:00 a.m. -9:00 a.m." into 24-hour `HH:MM` endpoints. */
export function parseHoursRange(text: string): { opens: string; closes: string } | null {
  const cleaned = text.replace(/\s+/g, ' ').trim();
  if (!cleaned || /closed/i.test(cleaned)) return null;

  const pattern = /(\d{1,2})(?::(\d{2}))?\s*([ap])\.?\s*m\.?/gi;
  const found: string[] = [];
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(cleaned)) !== null) {
    let hour = Number(match[1]) % 12;
    if (match[3].toLowerCase() === 'p') hour += 12;
    found.push(`${String(hour).padStart(2, '0')}:${match[2] ?? '00'}`);
  }

  return found.length >= 2 ? { opens: found[0], closes: found[1] } : null;
}

interface VenueSeed {
  id: string;
  name: string;
  url: string;
  hours: DiningHours[];
}

/** Parse the hours table into one seed per venue. */
export function parseHoursPage(html: string): VenueSeed[] {
  const $ = cheerio.load(html);
  const table = $('table.dining-hours-table').first();
  if (table.length === 0) return [];

  const periods: Array<MealPeriod | null> = table
    .find('thead th')
    .toArray()
    .map((cell) => COLUMN_TO_PERIOD[$(cell).text().trim().toLowerCase()] ?? null);

  return table
    .find('tbody tr')
    .toArray()
    .map((row) => {
      const cells = $(row).find('td').toArray();
      if (cells.length === 0) return null;

      const link = $(cells[0]).find('a').first();
      const name = ($(cells[0]).text() || '').replace(/\s+/g, ' ').trim();
      if (!name) return null;

      const href = link.attr('href') ?? '';
      const hours: DiningHours[] = [];

      for (let index = 1; index < cells.length; index += 1) {
        const period = periods[index];
        if (!period) continue;
        const range = parseHoursRange($(cells[index]).text());
        if (range) hours.push({ period, ...range });
      }

      return {
        id: slugify(name),
        name,
        url: href ? new URL(href, ORIGIN).toString() : ORIGIN,
        hours,
      };
    })
    .filter((seed): seed is VenueSeed => seed !== null);
}

/** Parse the "menus at a glance" page into menu sections keyed by venue name. */
export function parseMenuPage(html: string): Map<string, DiningMenuSection[]> {
  const $ = cheerio.load(html);
  const byVenue = new Map<string, DiningMenuSection[]>();

  $('div.at-a-glance-menu').each((_, section) => {
    const anchor = ($(section).attr('id') ?? '').toLowerCase();
    const period = ANCHOR_TO_PERIOD[anchor];
    if (!period) return;

    $(section)
      .find('div.at-a-glance-menu__dining-location')
      .each((__, location) => {
        const name = $(location).find('h3').first().text().replace(/\s+/g, ' ').trim();
        if (!name) return;

        const items: DiningMenuItem[] = [];

        $(location)
          .find('div.at-a-glance-menu__meal-station')
          .each((___, station) => {
            const stationName = $(station).find('h4').first().text().replace(/\s+/g, ' ').trim();

            $(station)
              .find('li')
              .each((____, entry) => {
                const link = $(entry).find('a').first();
                const itemName = link.text().replace(/\s+/g, ' ').trim();
                if (!itemName) return;

                // Allergen/diet icons carry their label in `title`; blanks exist.
                const tags = $(entry)
                  .find('img.meal-station__allergen-icon')
                  .toArray()
                  .map((icon) => ($(icon).attr('title') ?? '').trim())
                  .filter(Boolean);

                const href = link.attr('href');

                items.push({
                  id: slugify(`${name}-${period}-${itemName}`),
                  name: itemName,
                  station: stationName || null,
                  tags: [...new Set(tags)],
                  url: href ? new URL(href, ORIGIN).toString() : null,
                });
              });
          });

        if (items.length === 0) return;

        const sections = byVenue.get(name) ?? [];
        sections.push({ period, items });
        byVenue.set(name, sections);
      });
  });

  return byVenue;
}

/** Combine hours and menus into the day payload the dining UI renders. */
export function buildDiningDay(
  date: string,
  seeds: VenueSeed[],
  menus: Map<string, DiningMenuSection[]>,
): DiningDay {
  const venues: DiningVenue[] = seeds.map((seed) => {
    const sections = menus.get(seed.name) ?? [];
    return {
      id: seed.id,
      name: seed.name,
      // Every venue on the hours table is a residential restaurant; UCLA's
      // quick-service venues are listed separately and are not parsed here.
      kind: 'residential-restaurant',
      url: seed.url,
      location: null,
      hours: seed.hours,
      menus: sections,
      open: seed.hours.length > 0,
    };
  });

  // Venues that publish a menu but are absent from the hours table still matter.
  for (const [name, sections] of menus) {
    if (venues.some((venue) => venue.name === name)) continue;
    venues.push({
      id: slugify(name),
      name,
      kind: 'residential-restaurant',
      url: ORIGIN,
      location: null,
      hours: [],
      menus: sections,
      open: sections.length > 0,
    });
  }

  return { date, venues: venues.sort((a, b) => a.name.localeCompare(b.name)) };
}

/** Emit one media item per open venue so dining appears in the unified feed. */
export function diningDayToMediaItems(day: DiningDay, attribution: string): MediaItem[] {
  return day.venues
    .filter((venue) => venue.open || venue.menus.length > 0)
    .map((venue) => {
      const periods = venue.hours.map((entry) => MEAL_PERIOD_LABELS[entry.period]);
      const dishCount = venue.menus.reduce((total, section) => total + section.items.length, 0);
      const firstService = venue.hours[0];

      return {
        id: makeId(SOURCE_ID, day.date, venue.id),
        sourceId: SOURCE_ID,
        kind: 'menu' as const,
        title: venue.name,
        url: venue.url,
        publishedAt: campusWallClockToIso(day.date, firstService?.opens ?? '08:00'),
        startsAt: firstService ? campusWallClockToIso(day.date, firstService.opens) : null,
        endsAt: null,
        excerpt:
          dishCount > 0
            ? `${dishCount} item${dishCount === 1 ? '' : 's'} across ${venue.menus.length} meal period${venue.menus.length === 1 ? '' : 's'}.`
            : 'Menu not published for this date.',
        image: null,
        categories: periods,
        authors: [],
        durationSeconds: null,
        location: venue.location,
        badges: venue.open ? periods.slice(0, 2) : ['Closed today'],
        attribution,
        dataMode: 'build' as const,
      };
    });
}

export interface DiningResult extends SourceResult {
  /** The full day payload; the dining page needs more than `MediaItem` carries. */
  day: DiningDay | null;
}

export async function loadDining(now: Date = new Date()): Promise<DiningResult> {
  const config = SOURCES[SOURCE_ID];
  const fetchedAt = now.toISOString();
  const date = campusDate(now);

  if (!config.enabled) {
    return {
      sourceId: SOURCE_ID,
      status: 'unavailable',
      items: [],
      day: null,
      fetchedAt,
      note: 'Disabled by configuration',
    };
  }

  try {
    // Settled independently: hours alone still make a useful page.
    const [hoursHtml, menuHtml] = await Promise.allSettled([
      fetchText(HOURS_URL),
      fetchText(`${MENU_URL}?date=${date}`),
    ]);

    if (hoursHtml.status === 'rejected' && menuHtml.status === 'rejected') {
      throw hoursHtml.reason instanceof Error
        ? hoursHtml.reason
        : new Error('UCLA Dining unreachable');
    }

    const seeds = hoursHtml.status === 'fulfilled' ? parseHoursPage(hoursHtml.value) : [];
    const menus = menuHtml.status === 'fulfilled' ? parseMenuPage(menuHtml.value) : new Map();
    const day = buildDiningDay(date, seeds, menus);

    if (day.venues.length === 0) {
      return {
        sourceId: SOURCE_ID,
        status: 'empty',
        items: [],
        day,
        fetchedAt,
        note: 'Dining pages loaded but no venues could be parsed — the upstream markup may have changed.',
      };
    }

    return {
      sourceId: SOURCE_ID,
      status: 'ok',
      items: diningDayToMediaItems(day, config.attribution),
      day,
      fetchedAt,
      note:
        menuHtml.status === 'rejected'
          ? 'Hours only — the menu page could not be retrieved.'
          : undefined,
    };
  } catch (error) {
    return {
      sourceId: SOURCE_ID,
      status: 'error',
      items: [],
      day: null,
      fetchedAt,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}
